### ISSUE TITLE
Drawings TODO

### ISSUE THREAD

**Issue by cinderellen** [cinderellen/feeandthefelines#1]
## Japan
- [x] Kinkakuji
- [ ] Fushimi Inari-taisha
- [x] Osaka Castle
- [x] Sushi
- [x] Udon noodles
- [x] Sashimi
- [x] Ryokucha 
- [x] Kimono
- [x] Zori
- [x] Tabi

## Germany
- [ ] Brandenburg Gate
- [ ] Reichstag
- [x] pretzel
- [ ] sauerkraut
- [x] strudels
- [x] Wiener Schnitzel
- [x] dirndl
- [x] Lederhosen Suspenders
- [x] Tyrolean (hat)

## Egypt 
- [ ] Giza Pyramid Complex
- [ ] Great Spinx of Giza
- [ ] Ful Mudammas
- [ ] Bamia
- [ ] Khoshaf
- [ ] ancient cuisine: Eish Masri(Eish Baladi)
- [ ] Uraeus 
- [ ] crook and flail
- [ ] Shendyt

## India
- [ ] Taj Mahal
- [ ] India Gate
- [ ] Dum aloo
- [ ] Puri Bhaji
- [ ] Ghooghra
- [ ] Lassi
- [ ] Lehenga Choli 
- [ ] Achkan/Sherwani
- [ ] Jutti

## Ireland 
- [ ] The Blarney Stone & Blarney Castle, 
- [ ]  --
- [ ] Limerick Ham
- [ ] Farl
- [ ] Barmbrack
- [ ] Pasties 
- [ ] Tartan Kilt
- [ ] Step Dance Dress
- [ ] Tara brooch
