### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by cinderellen** [cinderellen/feeandthefelines#2]
## TODO
- [ ] Make screen mockups to use for prototype
- [ ] Create prototype (using inVision or MarvelApp)
- [ ] Write list of interactions for user to complete
- [ ] Write quiz for user to complete  
- [ ] Create document to record actions and time taken
- [ ] Evaluate answers

## Protocol
* Introduce user to the concept, GoGlobal, and give background information. At this stage they are asked to withhold questions until completing the user tests.
* Prototype is given to user.
* User is required to perform a list of tasks using the digital prototype.
* While completing these tasks, users' reaction time and interactions with the application are observed and recorded. 
* User is given quiz to complete after completing series of tasks.
* User is thanked for partaking in the testing process.
